# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/xintu_work/ram/ram_ip/ram_ip.srcs/sources_1/ip/sp_ram_ip/sp_ram_ip.xci
# IP: The module: 'sp_ram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xintu_work/ram/ram_ip/ram_ip.srcs/sources_1/ip/sp_ram_ip/sp_ram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sp_ram_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/xintu_work/ram/ram_ip/ram_ip.srcs/sources_1/ip/sp_ram_ip/sp_ram_ip.xci
# IP: The module: 'sp_ram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xintu_work/ram/ram_ip/ram_ip.srcs/sources_1/ip/sp_ram_ip/sp_ram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sp_ram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
