# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/xintu_work/fifo/fifo_ip/fifo_ip.srcs/sources_1/ip/fifo_ip/fifo_ip.xci
# IP: The module: 'fifo_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xintu_work/fifo/fifo_ip/fifo_ip.srcs/sources_1/ip/fifo_ip/fifo_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/xintu_work/fifo/fifo_ip/fifo_ip.srcs/sources_1/ip/fifo_ip/fifo_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/xintu_work/fifo/fifo_ip/fifo_ip.srcs/sources_1/ip/fifo_ip/fifo_ip.xci
# IP: The module: 'fifo_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xintu_work/fifo/fifo_ip/fifo_ip.srcs/sources_1/ip/fifo_ip/fifo_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/xintu_work/fifo/fifo_ip/fifo_ip.srcs/sources_1/ip/fifo_ip/fifo_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
